### ISSUE TITLE
Why not contributing directly to pre-commit-hooks?

### ISSUE THREAD

**Issue by ssbarnea** [Lucas-C/pre-commit-hooks#11]
I found at least one useful hook here and I am wondering why you did not contribute them directly to https://github.com/pre-commit/pre-commit-hooks ?

Adding more external dependencies increases risks and if each functionality is installed from a different repository you easily endup with a build process that is flaky and also less secure (a forced push on one of repositories, one of them being hacked,...).

**Comment by Lucas-C** [comment]
Answering in https://github.com/pre-commit/pre-commit-hooks/pull/399

**Comment by Lucas-C** [comment]
Btw, I would have appreciated a comment that you went along and already created a PR with code from this repo
