### ISSUE TITLE
Project depends (implicitly) on both `python-Levenshtein` and `python-Levenshtein-wheels`

### ISSUE THREAD

**Issue by SnoopJeDi** [Lucas-C/pre-commit-hooks#20]
The changes introduced by #18 do not apply to [.pre-commit-config.yaml](https://github.com/Lucas-C/pre-commit-hooks/blob/556aa509296132b8e2477f0a3e33c9916232e748/.pre-commit-config.yaml#L30), which still declares a dependency on `python-Levenshtein`. Probably the config needs to be updated to declare `python-Levenshtein-wheels` as well, since it is a more recent fork of the former.

This came up in the #python channel on Freenode's IRC network when a user was confused by the apparent need for `gcc` caused by this change. It confused a few of us for a bit and I thought I'd document the problem here.

Aside: `fuzzywuzzy` works perfectly well without any extension modules, and depends on this speedup as an extra. Perhaps this project could do the same? :innocent:

**Comment by Lucas-C** [comment]
> `fuzzywuzzy` works perfectly well without any extension modules, and depends on this speedup as an extra. Perhaps this project could do the same?

Sounds good!
Do you want to edit your PR to put this in place?

**Comment by SnoopJeDi** [comment]
> Do you want to edit your PR to put this in place?

As I take a look at the `pre-commit` documentation, this might be trickier than I thought, because it seems like there's no equivalent concept of an "extra" on their end. The only option I can think up is to make two `py.test` hooks.

However, as I think about it, I'm not really sure why this discrepancy was a problem for the downstream user, since it's only in the `local` hook, not one you're publishing for others to use. Let me ask them, and if it seems like there's a valid concern there, I'll open a separate issue.
