### ISSUE TITLE
IndexError while removing license file in files containing just the license header

### ISSUE THREAD

**Issue by M5oul** [Lucas-C/pre-commit-hooks#25]
Hi, and thanks for this nice tool!

I found a bug, when trying to remove the header of a file which only contains the header (typically `__init__.py`), I get following error:
```bash
  File "site-packages/pre_commit_hooks/insert_license.py", line 206, in license_found
    if src_file_content[license_header_index + len(license_info.prefixed_license)].strip():
IndexError: list index out of range
```

https://github.com/Lucas-C/pre-commit-hooks/blob/296f9eb522687001186e058e14408731859ccdc6/pre_commit_hooks/insert_license.py#L206

I added a `-1` in the equation and it fixes the issue. I tried to go a bit further by fixing how `license_header_index` is computed, but I am afraid I don’t get everything, so I would prefer that you fix it the best way.

Thanks.

**Comment by Lucas-C** [comment]
Thank you for reporting the bug!

I'm going to get a look a this.

**Comment by Lucas-C** [comment]
Fixed in https://github.com/Lucas-C/pre-commit-hooks/commit/c7dd3ca64c258962fb920c895fd5eee63df1bd32
