### ISSUE TITLE
Dropped py2 in patch version?

### ISSUE THREAD

**Issue by danielhoherd** [Lucas-C/pre-commit-hooks#34]
I was just looking over <https://github.com/Lucas-C/pre-commit-hooks/compare/v1.1.13...v1.1.14> and it looks like you dropped support for python2 in a patch version. Seems like that should've been done in a minor or major version. Just wanted to point that out. It doesn't affect me, but also doesn't conform to change standards of semver.

**Comment by Lucas-C** [comment]
You are right, I did not realize that 😔
Thank you for notifying me, and sorry for the annoyance.
This only applies to the `insert-license` hook though.
Sadly, we never tested Python 2 as part of the CI pipeline, even when we used to employ Travis CI.
I temporarily restored support for Python 2 in https://github.com/Lucas-C/pre-commit-hooks/pull/35
and will now perform new patch & minor releases

**Comment by Lucas-C** [comment]
Things should now be cleaner: https://github.com/Lucas-C/pre-commit-hooks/releases
