### ISSUE TITLE
insert_license - write file back in original  encoding

### ISSUE THREAD

**Issue by mdeweerd** [Lucas-C/pre-commit-hooks#39]
In insert_license.py we can red:

```python
    for encoding in ('utf8', 'ISO-8859-1'):  # we could use the chardet library to support more encodings
```

But when writeing the file back, utf8 is used, so the original file encoding could be changed.

It would be better to remember the original encoding to reuse it on writeback.

**Comment by Lucas-C** [comment]
Agreed, that would be better.

Have you faced a case where the wrong encoding was used on writeback?
I guess this line makes it very likely to happen:
https://github.com/Lucas-C/pre-commit-hooks/blob/v1.2.0/pre_commit_hooks/insert_license.py#L233

**Comment by mdeweerd** [comment]
Yes, I was faced with that.

**Comment by Lucas-C** [comment]
I submitted #44 in order to implement this
