### ISSUE TITLE
Newline is forced between license comment and code

### ISSUE THREAD

**Issue by oerp-odoo** [Lucas-C/pre-commit-hooks#49]
Even if I force remove `newline` on my `license_header.txt` file (in other words to not have newline as ending), it still adds newline between code. There should be an option to ignore newline. So it would be possible to get this:

```python
############
# My LICENSE
############
import blabla
```

instead of:

```python
############
# My LICENSE
############

import blabla
```

**Comment by Lucas-C** [comment]
Agreed.
This newline comes from here: https://github.com/Lucas-C/pre-commit-hooks/blob/master/pre_commit_hooks/insert_license.py#L87
PRs are welcome to add a new CLI option to disable it 😊

**Comment by Lucas-C** [comment]
Oh I see you have already opened #50!
Great 😊
