### ISSUE TITLE
add ignore-files argument to remove-crlf?

### ISSUE THREAD

**Issue by ahgraber** [Lucas-C/pre-commit-hooks#53]
Generally I want to replace/remove CRLF in my repos.  However, there are times where I require CRLF endings in files.  It would be very beneficial to have an `--ignore-files` argument that would take file names or globs and ignore them.

**Comment by Lucas-C** [comment]
Alright, sur, this could be added.
Do you want to submit a PR ?

**Comment by Lucas-C** [comment]
Sorry for the lack of response 😢

Actually, `pre-commit` already provides a builtin feature to do this: `exclude`
_cf._ https://pre-commit.com/#config-exclude
