### ISSUE TITLE
python-Levenshtein-wheels not available for python 3.10

### ISSUE THREAD

**Issue by daniela-winkler** [Lucas-C/pre-commit-hooks#55]
I recently upgraded my python version to 3.10 and found out that python-Levenshtein-wheels are not maintained anymore. To my knowledge there is a fork of this library with python 3.10 support:  https://pypi.org/project/Levenshtein/ 
I would appreciate if you adapt the dependencies.

**Comment by Lucas-C** [comment]
This is related to #18 & #19

Based on the latest comment on https://github.com/ztane/python-Levenshtein/issues/61
I think we can go back to `python-Levenshtein`.

Wold you like to submit a PR?

**Comment by daniela-winkler** [comment]
Thank you for accepting my changes. Unfortunately, using python-Levenshtein causes problems for Windows users while everything works fine for Linux users. When using Windows, I'm able to install https://pypi.org/project/Levenshtein/. Would you mind if I adapt the dependencies (again)?

**Comment by Lucas-C** [comment]
Sure, feel free to ubmit a PR!

Also, if you are familiar with GitHub actions, adding a pipeline execution in a Windows would be very welcome to ensure compatibility with this OS is validated.

**Comment by vfazio** [comment]
now that 1.3.1 is tagged, this should be closed?

**Comment by Lucas-C** [comment]
> now that 1.3.1 is tagged, this should be closed?

You are right, but given that the latest release seem to have caused issues for Windows users,
I'm going to wait for PR #57 to be released before closing this.

**Comment by Lucas-C** [comment]
Fixed by https://github.com/Lucas-C/pre-commit-hooks/pull/58
