### ISSUE TITLE
Rename this repo?

### ISSUE THREAD

**Issue by nrbnlulu** [Lucas-C/pre-commit-hooks#69]
AFAIK pre-commit hooks repo should not have "pre-commit" in the name they usually use `mirrors` or some other convention.

**Comment by Lucas-C** [comment]
Hi @nrbnlulu 

How is the repo name a problem for you?

This repository contains orginal code for some `pre-commit` hooks,
it's not a mirror for making available some existing tools as `pre-commit` hooks.

Hence, I don't really see the need to rename it

**Comment by nrbnlulu** [comment]
Hi @Lucas-C , I don't have any problem (I don't even use this repo) Just wanted light that point for you...

**Comment by nrbnlulu** [comment]
https://github.com/pre-commit/pre-commit.com/pull/755#event-8615956254
