### ISSUE TITLE
Ignore commit amend message files in .git when running forbid-tabs & co by default

### ISSUE THREAD

**Issue by xaver-k** [Lucas-C/pre-commit-hooks#74]
When amending to an existing commit, forbid-tabs detects tabs in the `git/COMMIT_EDITMSG` and fails the check. The tab is part of the message that is auto-generated by git to inform about the history of the commit, so it is not the user's fault.

Example output:
```
$ git commit --amend
No-tabs checker..........................................................Failed 
- hook id: forbid-tabs
- exit code: 1

Tabs detected in file: .git/COMMIT_EDITMSG 
```

Example git message:
```
title

original message

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Date:      Mon Apr 24 12:40:35 2023 +0200
#
# On branch xxxxxxxxxxxxxxx
#
# Changes to be committed:
#       modified:   ../some_file.hpp   <- This line has a tab in the terminal, but github helpfully replaces tabs with spaces....
#
```

The file should probably be ignored by the hook by default. However, I am not sure what the best approach for that would be here.
Options are to either ignoring the specific file (might not be enough in similar scenarios) OR a set of specific files (which ones) or everything in .git (might break some use-cases).

**Comment by Lucas-C** [comment]
Hi @xaver-k!

I agree that this would make sense.

You can already use the `exclude` entry in `.pre-commit-config.yaml` to ignore those files:
https://pre-commit.com/#regular-expressions

We could also probabky add this entry in the https://github.com/Lucas-C/pre-commit-hooks/blob/master/.pre-commit-hooks.yaml file in this repository

**Comment by xaver-k** [comment]
Hi @Lucas-C 
Interestingly I cannot reproduce the issue with a fresh git repository on my private machine, even though I could easily reproduce it at work on multiple machines. So I will need to investigate the root-cause a little further. Since I am on holiday right now and do not have access to my work-machine, that will first be in 2,5 weeks. I will keep you updated with what I find. 

Regarding a fix: I would prefer to fix the root cause here via a PR and just bump the version in all of my repositories instead of maintaining a workaround through a custom `exclude` in each repo (and I am using your hooks in a lot of repos, thank you for providing them, by the way  :smile:  )

**Comment by Lucas-C** [comment]
Alright, no hurry!
Thank you for investigating this.

I wish nice holidays!

And sure, a PR would be welcome

**Comment by xaver-k** [comment]
So, I found the root-cause now and have a reproduce: https://github.com/xaver-k/no-tabs-pre-commit-hook-bug-reporduce

The issue is that the hook does not explicitly defines which stages to run at (see https://pre-commit.com/#hooks-stages), so it just runs for all stages. This means that in our case, it is also run at the `commit-msg`-stage and therefore checks the message.

If it works for you, I would make a PR that confines the hooks to only run at the following stages:
* [pre-commit](https://pre-commit.com/#pre-commit)
* [pre-push](https://pre-commit.com/#pre-push)
* [pre-merge-commit](https://pre-commit.com/#pre-merge-commit)

For the other stages, I do not see a usecase for checking tabs / line endings:
* [commit-msg](https://pre-commit.com/#commit-msg)
* [post-checkout](https://pre-commit.com/#post-checkout)
* [post-merge](https://pre-commit.com/#post-merge)
* [post-rewrite](https://pre-commit.com/#post-rewrite)

* [pre-rebase](https://pre-commit.com/#pre-rebase)
* [prepare-comit-msg](https://pre-commit.com/#prepare-commit-msg)

**Comment by Lucas-C** [comment]
Makes sense!

I'm not even sure the `pre-push` is required

**Comment by Lucas-C** [comment]
CLosing as #75 was merged

Thank you @xaver-k!
