### ISSUE TITLE
CSS (single line comments) set `//`

### ISSUE THREAD

**Issue by njzjz** [Lucas-C/pre-commit-hooks#76]
To my knowledge, CSS doesn't allow `//`. Only `/* */` is allowed.

https://github.com/Lucas-C/pre-commit-hooks/blob/3ac999a6365629f44d4e3b8ef0bd8fac5f94c71e/README.md?plain=1#L69

**Comment by Lucas-C** [comment]
Alright

Do you want to submit a PR to fix this typo in the README.md?
