### ISSUE TITLE
chmod hook conflicts with shell chmod in a python virtual env

### ISSUE THREAD

**Issue by vtexier** [Lucas-C/pre-commit-hooks#80]
In a Python virtualenv configuration, the new `chmod` hook is placed in the virtualenv `bin` directory.

`source .venv/bin/activate `

add `.venv/bin` at the start of the `$PATH` env var.

Then using `chmod` command in shell fails :

```bash
chmod u+x
Incorrect octal permissions provided in configuration: invalid literal for int() with base 8: 'u+x'
```
```bash
which chmod
.venv/bin/chmod
```

**Workaround:** downgrade to version v1.4.2

**Proposed solution:** rename `chmod` hook to` pre_commit_chmod` ?

**Comment by Lucas-C** [comment]
Thank you for the report @vtexier!

I fixed that in https://github.com/Lucas-C/pre-commit-hooks/releases/tag/v1.5.2

Could you confirm that it solved your problem?

**Comment by vtexier** [comment]
I confirm that  https://github.com/Lucas-C/pre-commit-hooks/releases/tag/v1.5.2 release solves the problem.

Thank you for your quick fix and release !
I close the issue.
