### ISSUE TITLE
breaking changes in 1.5.2 and 1.5.3 - InvalidManifestError

### ISSUE THREAD

**Issue by tyriis** [Lucas-C/pre-commit-hooks#83]
It seem that something is not working as expected in the latest version

```
pre-commit version: 3.1.0
git --version: git version 2.41.0
sys.version:
    3.10.10 (main, Feb  7 2023, 12:19:31) [GCC 12.2.0]
sys.executable: /nix/store/syz2y6j53y5hpzbs7l0965zwxshi8iyl-python3-3.10.10/bin/python3.10
os.name: posix
sys.platform: linux
```

### error information

```
An error has occurred: InvalidManifestError: 
==> File ~/.cache/pre-commit/repofbad9rxa/.pre-commit-hooks.yaml
==> At Hook(id='forbid-crlf')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
Check the log at ~/.cache/pre-commit/pre-commit.log
```

It seems, that version constraint check is not working as it should, but I am sure it is not related to the hook but to the framework.

**Comment by tyriis** [comment]
maybe the pre-commit version is the issue, using the one from arch (aur) packages but seem to be not maintained :(, will check with latest version

**Comment by tyriis** [comment]
same issue with pre-commit 3.1.0

**Comment by tyriis** [comment]
From my point of view this is a breaking change and should not be introduced without a major (or at least minor) version and a note in the Release info. I am using your hooks everywhere and managing the upgrade with renovate (as many others).

**Comment by tyriis** [comment]
for people looking for a solution: upgrade to pre-commit latest version (currently 3.3.3) and it will work.

On Arch I am not able to switch to the 3.3.3 version natively therefore I use [nix](https://wiki.archlinux.org/title/Nix) to bypass the aur packaging system (use channel unstable) `nix-shell -p pre-commit` or `nix-shell -p pre-commit --run zsh`

**Comment by Lucas-C** [comment]
> It seems, that version constraint check is not working as it should, but I am sure it is not related to the hook but to the framework.

The new `stages` entry was added in `.pre-commit-hooks.yaml` by @xaver-k in PR https://github.com/Lucas-C/pre-commit-hooks/pull/75

The `stages` used have been introduced in `pre-commit` version 3.2.0:
https://github.com/pre-commit/pre-commit/blob/main/CHANGELOG.md#320---2023-03-17

This means that this hook since [v1.5.2](https://github.com/Lucas-C/pre-commit-hooks/releases/tag/v1.5.2) must be used with `pre-commit` 3.2.0 or superior. I'm going to add that to the `README.md` and mention in the latest releases.
