### ISSUE TITLE
make `forbid-tabs` and `replace-tabs` accept an exclusion list

### ISSUE THREAD

**Issue by AliSajid** [Lucas-C/pre-commit-hooks#86]
I am trying to use this for a project to make sure i have consistency in tabs v spaces. However, there are certain tab-separated- value files that I would want to keep untouched. I can't find some way to exclude those files. Having an exclusion argument would be very helpful.

**Comment by Lucas-C** [comment]
Have you considered using the standard `exclude` configuration entry?

_cf._ https://pre-commit.com/#top_level-exclude

**Comment by Lucas-C** [comment]
There 7 usage examples of this configuration entry in there:
https://github.com/Lucas-C/pre-commit-hooks/blob/master/.pre-commit-config.yaml

**Comment by AliSajid** [comment]
Thank you. That would help in this case. However I would really appreciate it if we could set it on a per-hook basis in case we need to exclude a group from just these hooks rather than globally.

**Comment by Lucas-C** [comment]
> Thank you. That would help in this case. However I would really appreciate it if we could set it on a per-hook basis in case we need to exclude a group from just these hooks rather than globally.

You may want to read more carefully the link I pointed you to.
This IS already a per-hook setting: https://github.com/Lucas-C/pre-commit-hooks/blob/master/.pre-commit-config.yaml#L23
