### ISSUE TITLE
Feature Request (insert_license): Dynamic years in license

### ISSUE THREAD

**Issue by ThomasMarwitzQC** [Lucas-C/pre-commit-hooks#89]
Hi folks,

first of all - thanks for this tool :)

I propose a new flag `--dynamic-years` which determines the start year of the copyright time range automatically - based on when the file was first tracked with GIT. If a start year is already present, it is _not_ touched. The end year is automatically set to the current year (`--use-current-year` is activated automatically when `--dynamic-years` is present).

The syntax in the `License.txt` could be as follows:

```
Copyright (C) {year_start}-{year_end}, PearCorp, Inc.
SPDX-License-Identifier: LicenseRef-PearCorp
```

To be discussed: I also considered a flag to determine _just_ the _start year_ dynamically. This, however, would lead to some inconsistencies regarding the logic to update year ranges. This is due to the fact that `update_year_range` only works when `--use-current-year` is supplied (`update_year_range=args.use_current_year`). My proposal, therefore, features a flag to determine **both years** automatically. 

To be discussed: Whether the `{year_start} / {year_end}` syntax should be used. Currently, this syntax isn't used in this repository but I think that it suits this case well as it clearly communicates in the LICENSE file that the start and end year is not set there, but determined automatically. However, I'm open to suggestions.

Use cases: When introducing license headers to a new repository, all year ranges per file are adjusted automatically.
Simply run `pre-commit run insert-license --all-files`. 

If you agree that this feature is useful, I'm happy to contribute by creating a PR.

Edit: Introduce `{year_end}` directly in the proposal.

**Comment by Lucas-C** [comment]
Hi @ThomasMarwitzQC

Have you read this section of the documentation?
https://github.com/Lucas-C/pre-commit-hooks#handling-years-flexibly

Handling years ranges is already supported
Maybe the options `--allow-past-years` & `--use-current-year` could provide what you are looking for?

**Comment by ThomasMarwitzQC** [comment]
Hi @Lucas-C, 

thanks for your response. 

I needed an extra functionality to check the git stats (last time a file was changed according to git) to determine the end year. 

If just using the flag `--use-current-year`, CI would break after New Year's Eve because we rung pre-commit checks there.

In the end, I went with creating a fork and including these changes there :)
