### ISSUE TITLE
An error has occurred: InvalidManifestError

### ISSUE THREAD

**Issue by alexisottonkpler** [Lucas-C/pre-commit-hooks#90]
Hey 👋 

since a few weeks, I have an error when running my pre-commit :

```
An error has occurred: InvalidManifestError: 
==> File /Users/alexisotton/.cache/pre-commit/repoiey05pzu/.pre-commit-hooks.yaml
==> At Hook(id='forbid-crlf')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
```

Here are my env infos :
```
pre-commit --version: 3.5.0
git --version: 2.24.3
python3 --version: Python 3.11.6
sys.platform: MacOS monterey 12.6.7
```

Here is my `pre-commit-config.yaml` part in error :
```
- repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
        exclude_types: [svg]
      - id: remove-crlf
        exclude_types: [svg]
```

I've looked at [this similar issue](https://github.com/Lucas-C/pre-commit-hooks/issues/83), but my `pre-commit`version look good

Thank's for your help

**Comment by Lucas-C** [comment]
Hi @alexisottonkpler

Have you see this previous issue?
https://github.com/Lucas-C/pre-commit-hooks/issues/83#issuecomment-1675215783

**Comment by alexisottonkpler** [comment]
yes. As I understand, `pre-commit` has to be upgraded to latest version (3.3.3 in this issue), mine is 3.5.0

**Comment by lordfolken** [comment]
Debian 12 only supplies pre-commit 3.0.4
I can work around it, but still a lot of things will break, that don't specifically install the latest version.
